---
- name: Fetch Running pods in namespace {{ application.namespace }}
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ application.namespace }}"
    field_selectors:
      - status.phase=Running
  register: pods_result
  failed_when: "'resources' not in pods_result"

- name: Identify list of pods for {{ application.kind }} {{ application.name }}
  set_fact:
    pods: "{{ pods | default([]) | selectattr('metadata.ownerReferences[0].name', '==', application.name) | map(attribute='metadata') | map('combine', {'node': item.spec.nodeName}) | selectattr('name', 'match', '^{{ application.name }}-[^-]+-[0-9]+$') | list }}"
  loop: "{{ pods_result.resources }}"
  loop_control:
    label: "{{ item.metadata.name }}"
