---
# tasks file for PacketCapture
- name: Configure PacketCapture
  ansible.builtin.include_tasks: "{{ tasks }}"
  loop:
    - discover_pods.yml
    - create_configmap.yml
    - create_jobs.yml
  loop_control:
    loop_var: tasks