apiVersion: monitoring.openshift.tpg/v1alpha1
kind: PacketCapture
metadata:
  labels:
    app.kubernetes.io/name: packet-capture
    app.kubernetes.io/instance: packet-capture-scooby-shaggy
    app.kubernetes.io/part-of: packet-capture-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: packet-capture-operator
  name: packet-capture-scooby-shaggy
  namespace: packet-capture
spec:
  jobId: "zxcv"
  targetNamespace: scooby
  targetDeployment: shaggy
  duration: "30"
  completionTimestamp: "2023-02-17T02:48:04Z"
