---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: packetcaptures.monitoring.openshift.tpg
spec:
  group: monitoring.openshift.tpg
  names:
    kind: PacketCapture
    listKind: PacketCaptureList
    plural: packetcaptures
    singular: packetcapture
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: PacketCapture is the Schema for the packetcaptures API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            type: object
            description: Spec defines the desired state of PacketCapture
            properties:
              jobId:
                description: Unique id of the Packet Capture job (4 characters only)
                type: string
              targetNamespace:
                description: Namespace containing the Deployment that maintains the pods to be monitored
                type: string
              targetDeployment:
                description: Deployment that maintains the pods to be monitored
                type: string
              port:
                description: The TCP/IP port to perform the packet capture against
                type: integer              
              completionTimestamp:
                description: complationTimestamp is a timestamp representing the server time when this packet capture should stop. Timing may not be exact and packet capture will cease soon after this time.  It is represented in RFC3339 form and is in UTC.
                type: string
#            x-kubernetes-validations:
#              - rule: "self.port < 65535"
#                message: "port should be zero or a positive integer less than 65535"
#              - rule: "self.port > 0"
#                message: "port should be zero or a positive integer less than 65535"
#              - rule: "size(self.jobId) != 4"
#                message: "jobId must be a 4 character string"
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: Status defines the observed state of PacketCapture
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
